---
# We're not installing OTEL on dev for now. Maybe a good idea later.
- name: Apply common configuration to all servers
  hosts: all
  become: true
  roles:
    - common
    - geerlingguy.security
    - geerlingguy.docker
# Not installing wanderer
- name: (DEV) Install spoopy services
  hosts: spoopy
  become: true
  vars:
    buyback_domain: "{{ sub_domains[1] }}.{{ domain_name }}"
    landing_domain: "{{ sub_domains[0] }}.{{ domain_name }}"
    sub_domains:
      - "dev"
      - "dev.buyback"
    # Adding images here in case we need to bump in dev for testing purposes.
    buyback_postgres_image: "postgres:16-alpine"
    buyback_redis_image: "redis:7-alpine"
    traefik_godns_image: "ghcr.io/timothyye/godns:3.2.4"
  roles:
    - traefik
    - landing
    - buyback
  