---
collections:
  - name: ansible.posix
    version: ">=1.5.4"
  - name: community.general
    version: ">=7.5.0"
  - name: community.docker
    version: ">=4.5.2"
roles:
  - name: geerlingguy.docker
    version: 7.4.7
  - name: geerlingguy.security
    version: 3.0.0
