---
collections:
  - name: ansible.posix
    version: ">=1.5.4"
  - name: community.general
    version: ">=7.5.0"
roles:
  - name: geerlingguy.docker
    version: 6.0.0
  - name: geerlingguy.ntp
    version: 2.7.0 