---
- name: Apply common configuration to all servers
  hosts: all
  become: true
  roles:
    - common
    - geerlingguy.security
    - otel
    - geerlingguy.docker
- name: Install spoopy services
  hosts: spoopy
  become: true
  roles:
    - traefik
    - landing
    - buyback
    - wanderer
