---
- name: Apply common configuration to all servers
  hosts: all
  become: true
  roles:
    - common
    - geerlingguy.security
    - geerlingguy.docker
    # - otel
- name: Install buyback services
  hosts: spoopy
  become: true
  roles:
    - traefik
    - buyback
    - wanderer
