---
- name: Make sure that current user has docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Create caddy directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/caddy"
    state: directory
    mode: "0755"

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ ansible_env.HOME }}/caddy/docker-compose.yml"
    mode: "0644"

- name: Run docker compose up
  community.docker.docker_compose_v2:
    project_src: "{{ ansible_env.HOME }}/caddy"
    project_name: "caddy"
    files:
      - docker-compose.yml
