buyback_nginx_port: 8080
buyback_domain: "buyback.kurtwood.me"
buyback_csrf_trusted_origins: "http://localhost:8080 http://{{ buyback_domain }}"
buyback_allowed_hosts: "localhost,127.0.0.1,{{ buyback_domain }}"
buyback_postgres_image: "postgres:16-alpine"
buyback_redis_image: "redis:7-alpine"

wanderer_postgres_image: "postgres:16-alpine"
wanderer_image: "wandererltd/community-edition:latest"
wanderer_eve_route_builder_image: "dansylvest/eve-route-builder:main"
wanderer_web_app_url: "http://{{ wanderer_domain }}"
wanderer_domain: "wanderer.kurtwood.me"
