---
- name: Download OTEL Collector DEB
  ansible.builtin.get_url:
    url: "{{ otel_collector_deb_url }}"
    dest: /tmp/otelcol-contrib.deb
    mode: '0644'

- name: Install OTEL Collector
  ansible.builtin.apt:
    deb: /tmp/otelcol-contrib.deb
    state: present
    update_cache: true

- name: Create OTEL Collector directory
  ansible.builtin.file:
    path: /etc/otelcol-contrib
    state: directory
    mode: '0755'

- name: Add otelcol-contrib user to docker group
  ansible.builtin.user:
    name: otelcol-contrib
    groups: docker
    append: true

- name: Configure OTEL Collector
  ansible.builtin.template:
    src: otel-collector-config.yaml.j2
    dest: /etc/otelcol-contrib/config.yaml
    mode: '0644'
  notify: Restart otel-collector

- name: Enable and start OTEL Collector service
  ansible.builtin.systemd:
    name: otelcol-contrib
    state: started
    enabled: true
