---
- name: Apply common configuration to all servers
  hosts: all
  become: true
  roles:
    - common

- name: Configure web servers
  hosts: webservers
  become: true
  roles:
    - common
  # Add web-specific roles here

- name: Configure application servers
  hosts: appservers
  become: true
  roles:
    - common
  # Add app-specific roles here

- name: Configure database servers
  hosts: database
  become: true
  roles:
    - common
  # Add database-specific roles here 