---
- name: Clone repository
  ansible.builtin.git:
    repo: "https://github.com/olf-folks/spoopy-landing.git"
    dest: "{{ ansible_env.HOME }}/landing"
    version: "main"
    force: true

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ ansible_env.HOME }}/landing/docker-compose.yml"
    mode: "0600"

- name: Run docker compose up
  community.docker.docker_compose_v2:
    project_src: "{{ ansible_env.HOME }}/landing"
    project_name: "landing"
    files:
      - docker-compose.yml
    pull: always
    state: present

- name: Check if containers are running
  community.docker.docker_compose_v2:
    project_src: "{{ ansible_env.HOME }}/landing"
    project_name: "landing"
    files:
      - docker-compose.yml
    state: present
  register: compose_status

- name: Check if containers are running
  ansible.builtin.assert:
    that:
      - "compose_status is success"
    fail_msg: "Docker compose services are not running properly"
    success_msg: "All docker compose services are running successfully"
